#index:
#    path: /
#    controller: App\Controller\DefaultController::index

create_product:
  path: product
  controller: App\Controller\ProductController::createProduct
  methods: ['POST']

create_order:
  path: order
  controller: App\Controller\OrderController::createOrder
  methods: ['POST']

add_product_to_order:
  path: order/product/add
  controller: App\Controller\OrderController::addProductToOrder
  methods: ['POST']

read_order:
  path: order/{orderID}
  controller: App\Controller\OrderController::readOrder
  methods: ['GET']